import type { Metadata } from "next";
import { Figtree } from "next/font/google";
import "./globals.css";
import Container from "./components/container";
import Header from "./components/header";

const figtree = Figtree({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Cyfotok Academy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-gray-100 text-black overflow-y-scroll ${figtree.className} `}>
        <Container>
          <Header/>
          {children}
          </Container>
      </body>
    </html>
  );
}
