import type { Metadata } from "next";
import { Figtree, Poppins } from "next/font/google";
import "./globals.css";
import Container from "./components/container";
import Header from "./components/header";
import Footer from "./sections/Footer";

const figtree = Figtree({ subsets: ["latin"] });
// const poppins = Poppins({ weight: ["400", "500", "600", "700"], subsets: ["latin"] }); // Aadhi Told to me change a new font for poppins
export const metadata: Metadata = {
  title: "Cyfotok Academy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`bg-gray-100 text-black overflow-y-scroll ${figtree.className} `}
      >
        <Container>
          <Header />
          {children}
          <Footer />
        </Container>
      </body>
    </html>
  );
}
